name: project1
channels: 
  - conda-forge
  - defaults
dependencies:
  - ipython=8.1.1
  - nbconvert=6.4.5
  - numpy=1.22.2
  - python=3.10.2
  - opencv=4.5.5
  - scikit-image=0.19.2
  - pandas=1.4.1
  - bokeh=2.4.2
  - selenium=4.1.0
